### ISSUE TITLE
it wont boot

### ISSUE THREAD

**Issue by juanpy0223** [aahowe/Hackintosh-GIGABYTE-Z690I-UL-DDR4#2]
hello sr, thanks for sharing your work...

I have the same board you have, but with i5-12400, it begins to boot but it reboots itself....

I was trying to install Catalina 10.15.7, Big Sur 11.0.1 and Monterey, I get the same error in all of them

**Comment by juanpy0223** [comment]
I have built hackintosh before, but dont have experience with AlderLake (12th generation)


https://github.com/juanpy0223/Dell-Latitude-5490-8th-gen

**Comment by aahowe** [comment]
Check if the bios settings are the same as mine

**Comment by juanpy0223** [comment]
Ok, I will check, thanks

**Comment by juanpy0223** [comment]
Hello, I set the Bios, and got through installation process... But in the last step, right before booting into the system it restarts itself

**Comment by juanpy0223** [comment]
![16777878634727398111147795167123](https://user-images.githubusercontent.com/74636450/222541316-eea44b85-5197-4e15-b2cf-eba60c500807.jpg)


Any suggestion?

**Comment by aahowe** [comment]
Will is keep rebooting over and over again？

**Comment by juanpy0223** [comment]
> 

Yes, I g

**Comment by juanpy0223** [comment]
> Will is keep rebooting over and over again？

I got it to boot with 225v lan patch, in kernel section
